### ISSUE TITLE
F37 Json array indexing not possible at compose or compose info

### ISSUE THREAD

**Issue by mcattamoredhat** [virt-s1/rhel-edge#870]
After updating osbuild.repo and osbuild-composer.repo at Fedora 37 (repositories used at PR https://github.com/osbuild/osbuild-composer/pull/3020):

1. osbuild-69-1.20220928git8a7b6d3.fc37.noarch
2. osbuild-composer-65-1.20220929git94e870d.fc37.x86_64

Json array indexing is not possible to get COMPOSE_ID nor COMPOSE_STATUS.

[admin@mcattamo-fedora-37-221017 rhel-edge]$ jq -r 'body.build_id' /tmp/tmp.J2OXN077Pr/compose-start-ostree-ng-b1272ac0-4103-4f23-b4c2-888642a145a5.json
**jq: error (at /tmp/tmp.J2OXN077Pr/compose-start-ostree-ng-b1272ac0-4103-4f23-b4c2-888642a145a5.json:11): Cannot index array with string "body"**

[admin@mcattamo-fedora-37-221017 rhel-edge]$ sudo composer-cli --json compose info d196d71c-86f2-4008-a5d6-41e3b6ccbc4b | tee compose_info.json > /dev/null
[admin@mcattamo-fedora-37-221017 rhel-edge]$ jq -r '.body.queue_status' compose_info.json
**jq: error (at compose_info.json:4497): Cannot index array with string "body"**

**Comment by mcattamoredhat** [comment]
As a suggested workaround, is possible to prepend ".[]" to json string. Then the commands are successful: 

[admin@mcattamo-fedora-37-221017 rhel-edge]$ jq -r **'.[].body.build_id'** /tmp/tmp.J2OXN077Pr/compose-start-ostree-ng-b1272ac0-4103-4f23-b4c2-888642a145a5.json
d196d71c-86f2-4008-a5d6-41e3b6ccbc4b

[admin@mcattamo-fedora-37-221017 rhel-edge]$ jq -r **'.[].body.queue_status'** compose_info.json
FINISHED

**Comment by henrywang** [comment]
Resolved by PR https://github.com/virt-s1/rhel-edge/pull/1214
