### ISSUE TITLE
Fedora-iot-installer type image fails due to missing package

### ISSUE THREAD

**Issue by mcattamoredhat** [virt-s1/rhel-edge#871]
Fedora-iot-installer type image fails in Fedora 37 due to missing package.

Compose command of a fedora-iot-installer image type fails with the error following:

[admin@mcattamo-fedora-37-221017 rhel-edge]$ sudo composer-cli --json compose start-ostree --ref fedora/37/x86_64/iot --url http://192.168.100.1/repo installer fedora-iot-installer
[
    {
        "method": "POST",
        "path": "/api/v1/compose",
        "status": 500,
        "body": {
            "errors": [
                {
                    "id": "DepsolveError",
                    **"msg": "DNF error occurred: MarkingErrors: Error occurred when marking packages for installation: Problems in request:\nmissing packages: sil-scheherazade-fonts"**
                }
            ],
            "status": false
        }
    }
]

**Comment by henrywang** [comment]
It's fixed now. CI has iot-installer test covered for Fedora 37.
